### ISSUE TITLE
SmartThings Hub v3 with Multipurpose sensor doesn't work

### ISSUE THREAD

**Issue by fe01134** [ibm-watson-iot/gateway-smartthings#6]
I  was able to  
1. create the SmartThings MyApps in market place as was suggested,   I used the Classic App to setup MyApp
2 It accepted my credentials for Watson IOT Platform API Keys
3,  It didn't recognize my multipurposesensor that was verified to be connected and created data for temperature and vibration and connected and not connected.

How can I trouble shoot this?
Is this supported with SmartThings3.

**Comment by durera** [comment]
Unfortunately, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020 so this repository is being archived. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
